### ISSUE TITLE
Docker Compose Yaml 

### ISSUE THREAD

**Issue by RobinGiel** [andrieslouw/imagesweserv#301]
here is my current docker compose yml 
```
version: '3.5'
services:
  app:
    image: 'ghcr.io/weserv/images:5.x'
    container_name: weservimages
    shm_size: '1gb'
    ports:
      - 8082:80
    restart: always
    networks:
      - imagesweserv
networks:
  imagesweserv:
    external:
      name: imagesweserv
```

All of my other containers were very easy to add a reverse proxy to access a container with nginx proxy manager, expect this one. Is there something I'm doing wrong or missing? The container is running fine on http but when I want to access it using https with a reverse proxy I can't
