### ISSUE TITLE
404 Not found another container in docker-compose

### ISSUE THREAD

**Issue by maffinca69** [andrieslouw/imagesweserv#403]
Hi!

I have my own service that can give out pictures. For example, the address (server in docker-compose) http://localhost:81/media/image.png will return a valid and correct picture image.png
But if the same address is used to get a thumbnail image, I get a 404. At the same time curl call inside weserv container successfully downloads my image

```
WESERV_PORT - 8086
PUBLIC_PORT - 85
```

```yaml
version: '3'

services:
  server:
    build: ./unit
    working_dir: /var/www/
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT}:81"
    volumes:
      - ./unit/config.json:/docker-entrypoint.d/config.json
      - ./../.:/var/www
      - ${PUBLISH_FOLDER}:/media

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  weserv:
    image: maffinca69/weserv-arm64
    restart: unless-stopped
    ports:
      - "${WESERV_PORT}:80"
    shm_size: '1GB'
```
maffinca69/weserv-arm64 - image for my mac (arm) without changes

```bash
curl --output te2.jpg http://server:81/media/image.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.9M  100 16.9M    0     0   320M      0 --:--:-- --:--:-- --:--:--  326M
```

<img width="682" alt="image" src="https://github.com/weserv/images/assets/35261681/2128b677-2b7a-4274-962f-c0cde645ea97">
